-- CREATE TABLE users (
--     user_id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     username varchar(50) NOT NULL UNIQUE,
--     email varchar(255) NOT NULL UNIQUE
-- );

-- CREATE TABLE tasks (
--     task_id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     user_id int REFERENCES users(user_id),
--     title varchar(255) NOT NULL,
--     priority int DEFAULT NULL,
--     due_date date DEFAULT NULL,
--     created_at timestamp NOT NULL DEFAULT NOW()
-- );